apiVersion: apps/v1
kind: Deployment
metadata:
    name: dummy-logger-deployment
spec:
    selector:
        matchLabels:
            app: dummy-logger-deployment
        template:
            mnetadata:
                labels:
                    app: dummy-logger-deployment
                spec:
                    containers:
                        - name: my-container
                        image: xawe/dummy-logger:2.0